### ISSUE TITLE
(live cd) VLC not working.

### ISSUE THREAD

**Issue by marek7400** [biglinux/biglinux-livecd#12]
(live cd) VLC not working OK. (run, 2 sec and close)
biglinux_2023-11-17_k65.iso

Solution working: 
Going into Settings/Add-Delete Software and removing "libva-vdpau-driver" helped (even though it dithered about needing it to run VLC)

**Comment by ruscher** [comment]
already fixed!

**Comment by marek7400** [comment]
Not fixed.
I download biglinux_2023-11-28_k61.iso run using Ventoy and still is problem.
VLC open mp3 OK, but MOV don't work.
VLC open -1 sec - and shut down.

**Comment by marek7400** [comment]
It appears to be a hardware/driver problem.
On another computer, VLC opens MOV files without a problem.

**Comment by marek7400** [comment]
Sometimes work boot with option:
2. Start with Open Source Drivers (support for OLD Nvidia GPUs or RHD, Intel and other computers)
